<a href="https://colab.research.google.com/github/pawel0508/NeuralNetworks/blob/main/Entropia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
np.set_printoptions(precision = 6, suppress = True)


Entropia rozkładu prawdopodobienstwa

In [3]:
def entropy(labels, base = None):
  if len(labels) <= 1:
    return 0
  
  from math import log, e
  n_labels = len(labels)
  value, counts = np.unique(labels, return_counts=True)
  probs = counts/n_labels
  n_classes = np.count_nonzero(probs)

  if n_classes <= 1:
    return 0
  ent = 0.

  base = e if base is None else base

  for i in probs:
    ent -= i * log(i, base)
  return ent





In [11]:

labels = [3, 2, 3, 2, 3, 3, 3]
entropy(labels)

0.5982695885852573

In [12]:
np.unique(labels, return_counts=True)

(array([2, 3]), array([2, 5]))

In [13]:
value, counts = np.unique(labels, return_counts=True)

In [14]:
counts/len(labels)

array([0.285714, 0.714286])

Binarna entropia krzyżowa

In [15]:
from tensorflow.keras.losses import binary_crossentropy

y_true = np.array([1, 0, 1, 1, 0, 1], dtype='float')
y_pred = np.array([0, 0, 1, 1, 0, 1], dtype='float')

binary_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=2.5708247450663957>

Entropia kategoryczna - Categorical crossentropy


In [16]:
from tensorflow.keras.losses import categorical_crossentropy

y_true = np.array([1, 0, 1, 1, 2, 0, 1, 1, 2], dtype='float')
y_pred = np.array([0, 0, 1, 1, 2, 0, 1, 2, 2], dtype='float')

categorical_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=30.23015636684835>