<a href="https://colab.research.google.com/github/pawel0508/NeuralNetworks/blob/main/Metryki.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
y_true = np.array([1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1])
y_pred = np.array([0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [51]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true, y_pred)


In [49]:
cm

array([[4, 1],
       [3, 6]])

In [36]:
cm[::-1]

array([[3, 6],
       [4, 1]])

In [47]:

cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1'], index=['true_0', 'true_1'])
cm

pred_0  pred_1
true_0       3       6
true_1       4       1

In [52]:

cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1'], index=['true_0', 'true_1'])
cm

pred_0  pred_1
true_0       4       1
true_1       3       6

In [9]:
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import plotly.figure_factory as ff

In [53]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true, y_pred)
def plot_confusion_matrix(cm):
    cm = cm[::-1]
    cm = pd.DataFrame(cm, columns=['pred_0', 'pred_1'], index=['true_1', 'true_0'])

    fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index), colorscale='ice', showscale=True, reversescale=True)
    fig.update_layout(width=500, height=500, title='Confusion Matrix', font_size=16)
    fig.show()

plot_confusion_matrix(cm)

In [42]:
np.array([
           [4,1],
           [3,6]
])[0]

array([4, 1])

In [54]:
cm

array([[4, 1],
       [3, 6]])

In [59]:
tn, fp, fn, tp = cm.ravel()

In [60]:
print(f'TN - True Negative: {tn}')
print(f'FP - False Positive: {fp}')
print(f'FN - False Negative: {fn}')
print(f'TP - True Positive: {tp}')

TN - True Negative: 4
FP - False Positive: 1
FN - False Negative: 3
TP - True Positive: 6


In [61]:
# False Positive Rate - Type I error
fpr = fp / (fp + tn)
print(fpr)

0.2


In [62]:
# False Negative Rate - Type II error
fnr = fn / (fn + tp)
print(fnr)

0.3333333333333333


In [63]:
# Precision - ile obserwacji przewidywanych jako pozytywne są w rzeczywistości pozytywne
precision = tp / (tp + fp)
print(precision)

0.8571428571428571


In [64]:
# Recall - jak wiele obserwacji z wzystkich poytywnych sklasyfikowaliśmy jako pozytywne
recall = tp / (tp + fn)
print(recall)

0.6666666666666666


In [65]:
from sklearn.metrics import roc_curve

In [66]:
fpr, tpr, tresh = roc_curve(y_true, y_pred, pos_label = 1)

In [67]:
roc = pd.DataFrame({'fpr' : fpr,
                    'tpr' : tpr})

In [71]:
def plot_roc_curve(y_true, y_pred):
    # Binary classification
    from sklearn.metrics import roc_curve
    fpr, tpr, tresh = roc_curve(y_true, y_pred, pos_label=1)

    fig = go.Figure(data=[go.Scatter(x=roc['fpr'], y=roc['tpr'], line_color='darkred', name='ROC Curve'),
                        go.Scatter(x=[0, 1], y=[0, 1], mode='lines', line_dash='dash', line_color='darkblue')],
                    layout=go.Layout(xaxis_title='False Positive Rate',
                                    yaxis_title='True Positive Rate',
                                    title='ROC Curve',
                                    showlegend=False,
                                    width=800, template = 'simple_white'))
    fig.show()
plot_roc_curve(y_true, y_pred)

#### AUC score

In [73]:
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(y_true, y_pred)

#### Gini

In [74]:
gini = roc_auc * 2 - 1

In [75]:
gini

0.46666666666666656

#### Metryki klasyfikacja wieloklasowa

In [76]:
y_true = np.array([1, 0, 1, 2, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2])
y_pred = np.array([0, 0, 1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 1, 2, 1, 2])

from sklearn.metrics import accuracy_score

accuracy_score(y_true, y_pred)

0.6842105263157895

Macierz konfuzji, pomyłek

In [82]:
cm = confusion_matrix(y_true, y_pred)
cm

array([[4, 1, 0],
       [3, 6, 1],
       [0, 1, 3]])

In [83]:
cm = cm[::-1]
cm = pd.DataFrame(cm, columns = ['y_pred_0', 'y_pred_1', 'y_pred_2'], index = ['y_true_2', 'y_true_1', 'y_pred_0'])

In [84]:
cm

y_pred_0  y_pred_1  y_pred_2
y_true_2         0         1         3
y_true_1         3         6         1
y_pred_0         4         1         0

In [92]:
fig = ff.create_annotated_heatmap(z=cm.values, x=list(cm.columns), y=list(cm.index), colorscale='blues', showscale=True, reversescale=True)
fig.update_layout(width=500, height=500, title='Confusion Matrix', font_size=16)
fig.show()

Raport klasyfikacji

In [94]:
from sklearn.metrics import classification_report
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.57      0.80      0.67         5
           1       0.75      0.60      0.67        10
           2       0.75      0.75      0.75         4

    accuracy                           0.68        19
   macro avg       0.69      0.72      0.69        19
weighted avg       0.70      0.68      0.68        19

