<a href="https://colab.research.google.com/github/pawel0508/NeuralNetworks/blob/main/NN_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import tensorflow as tf
import pandas as pd
import numpy as np 
import plotly.express as px

tf.__version__

'2.3.0'

### Wprowadzenie 

Model sekwencyjny to nic innego jak stos warstw.

In [4]:
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

Podstawowyn elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy ***Dense***.
Aby dodać warstwę do modelu należy użyć funkcji ***.add()***.

In [5]:
from tensorflow.keras.layers import Dense

model.add(Dense(units = 4, input_shape = (10, )))
print(model)

Wyświetlanie podsumowania modelu.

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 44        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


Dodanie kolejnej warstwy.

In [8]:
model.add(Dense(units = 2))

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 44        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 10        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


### Funkcje aktywacji

Istotnym elementem każdej sieci jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji są odpowiedzialne za aktywowanie odpowiednich neuronów w procesie uczenia. Jeżeli w procesie tworzenia warstwy nie określimy funkjci aktywacji, domyślnie stosowana jest ***liniowa*** funkcja aktywacji: $a(x) = x$. Warstwa z liniową funkcją aktywcji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stouje się różne funkcje aktywacji aby rozwiązać problemy nieliniowe.


In [26]:
from tensorflow.keras.activations import linear

random_data = sorted(np.random.randn(100))
df = pd.DataFrame({'data' : random_data, 'linear' : linear(random_data)})
df.head()

data    linear
0 -1.981645 -1.981645
1 -1.880549 -1.880549
2 -1.691449 -1.691449
3 -1.687139 -1.687139
4 -1.585322 -1.585322

In [27]:
px.line(data_frame = df, x = 'data', y = 'linear', template = 'simple_white',
        width = 900, height = 550, title = 'Activation: linear')

Sigmoid

In [28]:
from tensorflow.keras.activations import sigmoid

df = pd.DataFrame({'data' : random_data, 'sigmoid' : sigmoid(random_data)})

In [29]:
px.line(data_frame = df, x = 'data', y = 'sigmoid', template = 'simple_white',
        width = 900, height = 550, title = 'Activation: Sigmoid')

In [30]:
from tensorflow.keras.activations import relu
df = pd.DataFrame({'data' : random_data, 'relu' : relu(random_data)})
px.line(data_frame = df, x = 'data', y = 'relu', template = 'simple_white',
        width = 900, height = 550, title = 'Activation: Relu')

In [32]:
from tensorflow.keras.activations import tanh
df = pd.DataFrame({'data' : random_data, 'tanh' : tanh(random_data)})
px.line(data_frame = df, x = 'data', y = 'tanh', template = 'simple_white',
        width = 900, height = 550, title = 'Activation: Tanh')

### Model

In [33]:
model = Sequential()
model.add(Dense(units = 8, activation = 'relu', input_shape = (10, )))
model.add(Dense(units = 1, activation = 'sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


### Kompilacja modelu

Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określa się:

1. Rodzaj optymalizatora (Keras - Optymalizatory).
2. Funkcje straty (Keras - Straty).
3. Metryki które będziemy obserwować podczas trenowania sieci.

In [34]:
# klasyfikacja binarna
model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])
# klasyfikacja wieloklasowa 
model.compile(optimizer = 'rmsprop',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])
# regresja
model.compile(optimizer = 'rmsprop', 
              metrics = 'mse')


### Trenowanie modelu
Za dane wejściowe do modelu należy przekazywać obiekt Numpy arrays.
1. ***epochs*** - krotność przejścia danych przez sieć w procesie uczenia.
2. ***batch_size*** - rozmiar wsadu po którym następuje aktualizacja wag.
3. ***validation_split*** - część danych treninogowych, które zostaną wykorzystane jako zbiór walidacyjny.
4. ***validation_data*** - (x_val, y_val) - dane wykorzystane do walidacji modelu.


In [35]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### Przykład - klasyfikacja binarna.

In [36]:
data = np.random.randn(1000, 150)
labels = np.random.randint(2, size = (1000, 1))

In [37]:
print(data.shape)

(1000, 150)


In [38]:
print(labels.shape)

(1000, 1)


In [39]:
data[:3]

array([[ 4.14255991e-01, -9.31814046e-01,  8.80556480e-01,
        -1.88941394e+00,  8.62775783e-01, -6.39844050e-03,
        -1.48680209e+00,  1.13002560e+00, -4.02604217e-01,
         2.65044391e-01, -1.32361357e+00,  8.33256414e-01,
        -3.10110287e-01,  3.71443183e-01, -1.58765101e-01,
         7.88300993e-02,  3.70211831e-01, -1.81447787e+00,
         6.05915857e-01, -1.63483071e-01,  1.36192795e-01,
         2.70755116e-01,  2.48948661e-01,  1.94555302e+00,
        -9.87557256e-01,  2.68335572e-01, -1.24510474e+00,
         2.40040055e-01, -6.35887101e-01,  6.07982827e-01,
        -8.47980664e-01, -7.52157968e-01, -1.40481857e+00,
         8.41970020e-01,  2.46304419e+00,  2.87656825e-02,
        -1.17645494e+00, -7.82240355e-01, -2.10390656e+00,
         7.22426555e-01,  9.96979397e-02,  1.41440245e+00,
        -1.45608334e-01, -6.35512318e-01,  1.13737995e+00,
         1.41921045e+00,  1.33373495e+00,  8.06164367e-01,
         6.19518755e-01, -5.20891352e-01,  1.58935810e-0

In [40]:
labels[:10]

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0]])

In [41]:
model = Sequential()

In [43]:
model.add(Dense(units = 32, activation = 'relu', input_shape = (150, )))
model.add(Dense(units = 1, activation = 'sigmoid'))

model.compile(optimizer='rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 32)                4832      
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 33        
Total params: 4,865
Trainable params: 4,865
Non-trainable params: 0
_________________________________________________________________


In [45]:
model.fit(data, labels, epochs = 20)

Epoch 1/20
32/32 [==============================] - 0s 1ms/step - loss: 0.7449 - accuracy: 0.5360
Epoch 2/20
32/32 [==============================] - 0s 1ms/step - loss: 0.6839 - accuracy: 0.5860
Epoch 3/20
32/32 [==============================] - 0s 1ms/step - loss: 0.6412 - accuracy: 0.6230
Epoch 4/20
32/32 [==============================] - 0s 982us/step - loss: 0.6056 - accuracy: 0.6700
Epoch 5/20
32/32 [==============================] - 0s 978us/step - loss: 0.5751 - accuracy: 0.7150
Epoch 6/20
32/32 [==============================] - 0s 1ms/step - loss: 0.5462 - accuracy: 0.7420
Epoch 7/20
32/32 [==============================] - 0s 1000us/step - loss: 0.5218 - accuracy: 0.7700
Epoch 8/20
32/32 [==============================] - 0s 993us/step - loss: 0.4976 - accuracy: 0.7890
Epoch 9/20
32/32 [==============================] - 0s 997us/step - loss: 0.4753 - accuracy: 0.8040
Epoch 10/20
32/32 [==============================] - 0s 1ms/step - loss: 0.4523 - accuracy: 0.8230
Epoch 11

In [68]:
model_1 = Sequential()
model_1.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model_1.add(Dense(units = 1, activation = 'sigmoid'))
model_1.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])
model_1.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_21 (Dense)             (None, 32)                4832      
_________________________________________________________________
dense_22 (Dense)             (None, 1)                 33        
Total params: 4,865
Trainable params: 4,865
Non-trainable params: 0
_________________________________________________________________


In [69]:
model_1.fit(data, labels, epochs = 20, batch_size =30)

Epoch 1/20
34/34 [==============================] - 0s 1ms/step - loss: 0.7960 - accuracy: 0.5130
Epoch 2/20
34/34 [==============================] - 0s 975us/step - loss: 0.6960 - accuracy: 0.5870
Epoch 3/20
34/34 [==============================] - 0s 937us/step - loss: 0.6395 - accuracy: 0.6280
Epoch 4/20
34/34 [==============================] - 0s 1ms/step - loss: 0.5970 - accuracy: 0.6750
Epoch 5/20
34/34 [==============================] - 0s 951us/step - loss: 0.5604 - accuracy: 0.7200
Epoch 6/20
34/34 [==============================] - 0s 973us/step - loss: 0.5304 - accuracy: 0.7540
Epoch 7/20
34/34 [==============================] - 0s 1ms/step - loss: 0.5016 - accuracy: 0.7900
Epoch 8/20
34/34 [==============================] - 0s 1ms/step - loss: 0.4749 - accuracy: 0.8120
Epoch 9/20
34/34 [==============================] - 0s 970us/step - loss: 0.4486 - accuracy: 0.8360
Epoch 10/20
34/34 [==============================] - 0s 912us/step - loss: 0.4249 - accuracy: 0.8450
Epoch 1

In [66]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150, )))
model.add(Dense(units = 1, activation = 'sigmoid'))
model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_19 (Dense)             (None, 32)                4832      
_________________________________________________________________
dense_20 (Dense)             (None, 1)                 33        
Total params: 4,865
Trainable params: 4,865
Non-trainable params: 0
_________________________________________________________________


In [67]:
model.fit(data, labels, epochs = 20, batch_size = 32, validation_split = 0.2)

Epoch 1/20
25/25 [==============================] - 0s 6ms/step - loss: 0.8153 - accuracy: 0.5125 - val_loss: 0.7619 - val_accuracy: 0.5400
Epoch 2/20
25/25 [==============================] - 0s 2ms/step - loss: 0.7068 - accuracy: 0.5738 - val_loss: 0.7495 - val_accuracy: 0.5400
Epoch 3/20
25/25 [==============================] - 0s 2ms/step - loss: 0.6512 - accuracy: 0.6037 - val_loss: 0.7473 - val_accuracy: 0.5150
Epoch 4/20
25/25 [==============================] - 0s 2ms/step - loss: 0.6099 - accuracy: 0.6562 - val_loss: 0.7526 - val_accuracy: 0.5050
Epoch 5/20
25/25 [==============================] - 0s 2ms/step - loss: 0.5762 - accuracy: 0.7038 - val_loss: 0.7622 - val_accuracy: 0.5100
Epoch 6/20
25/25 [==============================] - 0s 2ms/step - loss: 0.5465 - accuracy: 0.7312 - val_loss: 0.7730 - val_accuracy: 0.4950
Epoch 7/20
25/25 [==============================] - 0s 2ms/step - loss: 0.5188 - accuracy: 0.7788 - val_loss: 0.7851 - val_accuracy: 0.4900
Epoch 8/20
25/25 [==

In [73]:

model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [76]:
pd.DataFrame(history.history)

loss  accuracy  val_loss  val_accuracy
0   0.748004   0.53500  0.751215         0.520
1   0.673271   0.60000  0.750224         0.540
2   0.631944   0.63875  0.751871         0.535
3   0.597228   0.68750  0.758025         0.525
4   0.566941   0.72000  0.763883         0.530
5   0.539225   0.73875  0.770881         0.540
6   0.513583   0.77500  0.779006         0.535
7   0.488932   0.80125  0.787669         0.520
8   0.464654   0.83750  0.797169         0.515
9   0.442457   0.85500  0.807472         0.515
10  0.420429   0.86750  0.815918         0.530
11  0.398688   0.88875  0.827483         0.535
12  0.377965   0.89625  0.838044         0.525
13  0.358494   0.91250  0.848328         0.530
14  0.337082   0.92625  0.858445         0.530
15  0.317096   0.93000  0.867954         0.525
16  0.297833   0.94500  0.879618         0.530
17  0.279520   0.95000  0.889323         0.545
18  0.260803   0.95125  0.900748         0.540
19  0.243343   0.96000  0.909902         0.545

In [78]:
test_data = np.random.randn(5,150)
test_labels = np.random.randint(2, size = (5,1))

In [81]:
model.predict(test_data)

array([[0.18944457],
       [0.7461901 ],
       [0.14634588],
       [0.5075339 ],
       [0.9671933 ]], dtype=float32)

In [83]:
model.predict_proba(test_data)

Instructions for updating:
Please use `model.predict()` instead.


array([[0.18944457],
       [0.7461901 ],
       [0.14634588],
       [0.5075339 ],
       [0.9671933 ]], dtype=float32)

In [84]:
model.predict_classes(test_data)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[0],
       [1],
       [0],
       [1],
       [1]], dtype=int32)

Przykład - klasyfikacja wieloklasowa


In [87]:
data = np.random.randn(1000, 150)
labels = np.random.randint(4, size = (1000, 1))

In [88]:
print(data.shape)
print(labels.shape)

(1000, 150)
(1000, 1)


In [89]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes = 10)
labels

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [90]:
labels[1]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [91]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(units = 10, activation = 'softmax'))

model.compile(optimizer = 'rmsprop',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])
model.fit(data, labels, batch_size = 10, epochs = 20, validation_split = 0.2, verbose = 0)

In [99]:
test_data = np.random.randn(10, 150)

In [100]:
model.predict(test_data)

array([[8.6757565e-01, 5.9627998e-03, 5.6954313e-02, 6.9507264e-02,
        6.8744027e-10, 4.6116718e-11, 1.9020918e-09, 2.6031990e-10,
        1.5137084e-09, 8.7376767e-10],
       [1.1012409e-01, 4.2888102e-01, 5.5033524e-02, 4.0595841e-01,
        1.7042859e-07, 9.1336666e-08, 1.4993611e-07, 1.8816446e-07,
        2.6969718e-07, 2.0606437e-06],
       [6.0466290e-02, 5.6938224e-02, 1.5889113e-01, 7.2370434e-01,
        1.8190383e-08, 2.8595160e-09, 3.0467906e-09, 5.5667053e-09,
        4.4556452e-09, 1.6202762e-08],
       [3.0904990e-01, 1.2562370e-01, 5.6091386e-01, 4.4124946e-03,
        3.1648708e-09, 1.2995591e-09, 9.9092923e-10, 1.2961405e-09,
        2.8018338e-10, 4.0991072e-10],
       [3.8229746e-01, 2.9906061e-01, 2.9200235e-01, 2.6639482e-02,
        1.5863325e-08, 2.2454534e-08, 3.1312513e-08, 2.0942107e-08,
        2.6990896e-09, 2.2593341e-08],
       [1.1950890e-02, 2.7229941e-01, 1.4711502e-01, 5.6863469e-01,
        4.5239142e-11, 1.3920975e-11, 1.4105968e-10, 2.08

In [101]:
model.predict_proba(test_data)

array([[8.6757565e-01, 5.9627998e-03, 5.6954313e-02, 6.9507264e-02,
        6.8744027e-10, 4.6116718e-11, 1.9020918e-09, 2.6031990e-10,
        1.5137084e-09, 8.7376767e-10],
       [1.1012409e-01, 4.2888102e-01, 5.5033524e-02, 4.0595841e-01,
        1.7042859e-07, 9.1336666e-08, 1.4993611e-07, 1.8816446e-07,
        2.6969718e-07, 2.0606437e-06],
       [6.0466290e-02, 5.6938224e-02, 1.5889113e-01, 7.2370434e-01,
        1.8190383e-08, 2.8595160e-09, 3.0467906e-09, 5.5667053e-09,
        4.4556452e-09, 1.6202762e-08],
       [3.0904990e-01, 1.2562370e-01, 5.6091386e-01, 4.4124946e-03,
        3.1648708e-09, 1.2995591e-09, 9.9092923e-10, 1.2961405e-09,
        2.8018338e-10, 4.0991072e-10],
       [3.8229746e-01, 2.9906061e-01, 2.9200235e-01, 2.6639482e-02,
        1.5863325e-08, 2.2454534e-08, 3.1312513e-08, 2.0942107e-08,
        2.6990896e-09, 2.2593341e-08],
       [1.1950890e-02, 2.7229941e-01, 1.4711502e-01, 5.6863469e-01,
        4.5239142e-11, 1.3920975e-11, 1.4105968e-10, 2.08

In [102]:
model.predict_classes(test_data)

array([0, 1, 3, 2, 0, 3, 3, 0, 0, 1])

### Przykład regresja

In [103]:
data = np.random.random((1000, 150))
labels = 50 * np.random.random(1000)

In [104]:
data[:3]

array([[0.65307335, 0.00619162, 0.90726794, 0.91947951, 0.43437353,
        0.78809903, 0.77540707, 0.4475071 , 0.65012962, 0.70399201,
        0.14385485, 0.45231397, 0.16135991, 0.76353907, 0.93498643,
        0.05930006, 0.80471512, 0.03730724, 0.06357292, 0.72684036,
        0.55190076, 0.39529675, 0.37972089, 0.5788766 , 0.39625379,
        0.8899904 , 0.30028327, 0.94902106, 0.9966471 , 0.94756656,
        0.37764663, 0.22811407, 0.37586539, 0.40109651, 0.07482254,
        0.99364927, 0.18368454, 0.34630815, 0.91051064, 0.43168913,
        0.25708079, 0.04642848, 0.76176993, 0.58820019, 0.23096597,
        0.87773583, 0.37136277, 0.37548447, 0.70464562, 0.19758536,
        0.82292542, 0.29361754, 0.61992975, 0.62001066, 0.42409979,
        0.54098644, 0.02608381, 0.22277813, 0.17742248, 0.17168954,
        0.87511136, 0.63817395, 0.64594774, 0.61812149, 0.86943823,
        0.72850398, 0.61852105, 0.27501744, 0.92498936, 0.63151019,
        0.9844028 , 0.90899412, 0.70063336, 0.46

In [105]:
labels[:10]

array([22.71765889, 37.13194384, 15.70741453, 20.16919482, 25.91263586,
       15.55965258, 19.90028628, 45.07096864, 35.22246752, 29.27042079])

In [106]:
model = Sequential()
model.add(Dense(units = 32, activation='relu', input_shape = (150,)))
model.add(Dense(1))
model.compile(optimizer = 'rmsprop',
              loss = 'mse')
model.summary()

Model: "sequential_16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_31 (Dense)             (None, 32)                4832      
_________________________________________________________________
dense_32 (Dense)             (None, 1)                 33        
Total params: 4,865
Trainable params: 4,865
Non-trainable params: 0
_________________________________________________________________


In [108]:
model.fit(data, labels, epochs = 10, batch_size=20, validation_split = 0.2)

Epoch 1/10
40/40 [==============================] - 0s 3ms/step - loss: 294.4285 - val_loss: 227.4595
Epoch 2/10
40/40 [==============================] - 0s 2ms/step - loss: 209.9484 - val_loss: 225.0438
Epoch 3/10
40/40 [==============================] - 0s 2ms/step - loss: 206.0488 - val_loss: 224.8127
Epoch 4/10
40/40 [==============================] - 0s 2ms/step - loss: 205.8430 - val_loss: 226.9427
Epoch 5/10
40/40 [==============================] - 0s 2ms/step - loss: 205.0695 - val_loss: 225.9890
Epoch 6/10
40/40 [==============================] - 0s 2ms/step - loss: 204.4277 - val_loss: 226.6593
Epoch 7/10
40/40 [==============================] - 0s 2ms/step - loss: 203.6791 - val_loss: 224.7771
Epoch 8/10
40/40 [==============================] - 0s 2ms/step - loss: 203.3537 - val_loss: 225.2492
Epoch 9/10
40/40 [==============================] - 0s 2ms/step - loss: 202.7698 - val_loss: 227.4765
Epoch 10/10
40/40 [==============================] - 0s 2ms/step - loss: 201.8002 

In [109]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150,)))
model.add(Dense(1))

model.compile(optimizer = 'rmsprop',
              loss = 'mae',
              metrics = ['mse'])


In [110]:
model.fit(data, labels, batch_size=32, epochs = 30, validation_split=0.2)

Epoch 1/30
25/25 [==============================] - 0s 5ms/step - loss: 20.5102 - mse: 597.4637 - val_loss: 16.0214 - val_mse: 396.7888
Epoch 2/30
25/25 [==============================] - 0s 2ms/step - loss: 15.2120 - mse: 335.6826 - val_loss: 13.5265 - val_mse: 251.8274
Epoch 3/30
25/25 [==============================] - 0s 2ms/step - loss: 12.9491 - mse: 227.2946 - val_loss: 13.1324 - val_mse: 223.2014
Epoch 4/30
25/25 [==============================] - 0s 2ms/step - loss: 12.4851 - mse: 206.4596 - val_loss: 13.3954 - val_mse: 230.3079
Epoch 5/30
25/25 [==============================] - 0s 2ms/step - loss: 12.4562 - mse: 206.5361 - val_loss: 13.3416 - val_mse: 228.4840
Epoch 6/30
25/25 [==============================] - 0s 2ms/step - loss: 12.4312 - mse: 206.3924 - val_loss: 13.5505 - val_mse: 236.4268
Epoch 7/30
25/25 [==============================] - 0s 2ms/step - loss: 12.3934 - mse: 207.5827 - val_loss: 13.2800 - val_mse: 226.3601
Epoch 8/30
25/25 [==============================

In [111]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[25.28812 ],
       [21.796162],
       [23.770124],
       [25.508307],
       [25.580063],
       [27.070723],
       [26.153406],
       [26.436975],
       [24.3725  ],
       [25.03829 ]], dtype=float32)