<a href="https://colab.research.google.com/github/pawel0508/NeuralNetworks/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensory

In [1]:
import numpy as np

In [2]:
scalar = 3
print(type(scalar))

<class 'int'>


In [3]:
scalar = 3.
print(type(scalar))

<class 'float'>


In [10]:
vector = np.array([1,2,4,-5])
print(f'Rozmiar wektora: {vector.shape}')
print(f'Rząd: {vector.ndim}')
print(f'Typ danych wektora: {vector.dtype}')
print(f'Długość wektora: {len(vector)}')

Rozmiar wektora: (4,)
Rząd: 1
Typ danych wektora: int64
Długość wektora: 4


In [12]:
macierz = np.array([
    [1,2,4,-5],
    [4,5,7,3]
])
print(f'Rozmiar macierzy: {macierz.shape}')
print(f'Rząd: {macierz.ndim}')
print(f'Typ danych macierzy: {macierz.dtype}')
print(f'Długość macierzy: {len(macierz)}')

Rozmiar macierzy: (2, 4)
Rząd: 2
Typ danych macierzy: int64
Długość macierzy: 2


In [13]:
macierz = np.array([
    [1,2,4,-5],
    [4,5,7,3],
    [4,4,7,8]
])
print(f'Rozmiar macierzy: {macierz.shape}')
print(f'Rząd: {macierz.ndim}')
print(f'Typ danych macierzy: {macierz.dtype}')
print(f'Długość macierzy: {len(macierz)}')

Rozmiar macierzy: (3, 4)
Rząd: 2
Typ danych macierzy: int64
Długość macierzy: 3


In [16]:
tensor = np.array([
                   [1,2,3,4],
                   [5,6,7,8]
])
print(f'Rozmiar tensora: {tensor.shape}')
print(f'Rząd: {tensor.ndim}')
print(f'Typ danych tensora: {tensor.dtype}')
print(f'Długość tensora: {len(tensor)}')

Rozmiar tensora: (2, 4)
Rząd: 2
Typ danych tensora: int64
Długość tensora: 2


In [17]:
tensor = np.array([
                  [[1,2,3,4],
                   [5,6,7,8]],
                   
                   [[1,2,3,4],
                    [5,6,7,8]]
])
print(f'Rozmiar tensora: {tensor.shape}')
print(f'Rząd: {tensor.ndim}')
print(f'Typ danych tensora: {tensor.dtype}')
print(f'Długość tensora: {len(tensor)}')

Rozmiar tensora: (2, 2, 4)
Rząd: 3
Typ danych tensora: int64
Długość tensora: 2


In [18]:
tensor = np.array([
                  [[1,2,3,4],
                   [5,6,7,8]],
                   
                   [[1,2,3,4],
                    [5,6,7,8]],
                   
                   [[1,2,3,4],
                    [5,6,7,8]]
])
print(f'Rozmiar tensora: {tensor.shape}')
print(f'Rząd: {tensor.ndim}')
print(f'Typ danych tensora: {tensor.dtype}')
print(f'Długość tensora: {len(tensor)}')

Rozmiar tensora: (3, 2, 4)
Rząd: 3
Typ danych tensora: int64
Długość tensora: 3


In [22]:
tensor = np.array([
    [[1, 2, 3, 4],
     [4, 5, 6, 4],
     [4, 2, 5, 2]],
    [[7, 8, 9, 8],
     [3, 7, 3, 9],
     [5, 2, 4, 3]],
    [[2, 3, 5, 4],
     [7, 2, 5, 1],
     [8, 2, 7, 2]],
    [[2, 3, 5, 7],
     [7, 2, 5, 9],
     [8, 2, 7, 0]],
    [[2, 3, 5, 7],
     [7, 2, 5, 9],
     [8, 2, 7, 0]]
])

print(tensor)
print(type(tensor))
print(f'Rozmiar macierzy: {tensor.shape}')
print(f'Typ danych macierzy: {tensor.dtype}')
print(f'Rząd: {tensor.ndim}')
print(f'Długosc: {len(tensor)}')

[[[1 2 3 4]
  [4 5 6 4]
  [4 2 5 2]]

 [[7 8 9 8]
  [3 7 3 9]
  [5 2 4 3]]

 [[2 3 5 4]
  [7 2 5 1]
  [8 2 7 2]]

 [[2 3 5 7]
  [7 2 5 9]
  [8 2 7 0]]

 [[2 3 5 7]
  [7 2 5 9]
  [8 2 7 0]]]
<class 'numpy.ndarray'>
Rozmiar macierzy: (5, 3, 4)
Typ danych macierzy: int64
Rząd: 3
Długosc: 5
